on:
  push:
    branches:
    - '**'
    tags-ignore:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
name: Stucco proto test
env:
  CGO_ENABLED: 0
jobs:
  gen:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    env:
      GRPC_WEB_VER: 1.2.1
      PROTOC_GO: v1.26.0
      PROTOC_GRPC_GO: v1.1
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.14'
    - uses: actions/checkout@v2
    - name: install global gen deps
      run: |
        mkdir -p "${HOME}/.local/bin"
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
        curl -L https://github.com/grpc/grpc-web/releases/download/$GRPC_WEB_VER/protoc-gen-grpc-web-$GRPC_WEB_VER-linux-x86_64 -o "${HOME}/.local/bin/protoc-gen-grpc-web"
        chmod +x "${HOME}/.local/bin/protoc-gen-grpc-web"
        go install google.golang.org/protobuf/cmd/protoc-gen-go@$PROTOC_GO
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@$PROTOC_GRPC_GO
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ hashFiles('package-lock.json') }}
    - name: install gen deps
      run: npm install
    - name: build
      run: npm run build
    - name: check clean
      run: |
        git diff
        git status
        [ "x$(git status --porcelain)" = "x" ] || (echo "generate libraries" && exit 1)
